/*
File nay de dinh nghia cac bien su dung nhieu lan trong ung dung
*/
// Type cua cac action lay ra
const URL = "http://localhost:3001/products"
const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST"
const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"
const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE"
const SEARCH_PRODUCT_REQUEST = "SEARCH_PRODUCT_REQUEST"
const SEARCH_PRODUCT_SUCCESS = "SEARCH_PRODUCT_SUCCESS"
const SEARCH_PRODUCT_FAILURE = "SEARCH_PRODUCT_FAILURE"
export {
    GET_PRODUCT_REQUEST,
    GET_PRODUCT_SUCCESS,
    GET_PRODUCT_FAILURE,
    SEARCH_PRODUCT_REQUEST,
    SEARCH_PRODUCT_SUCCESS,
    SEARCH_PRODUCT_FAILURE,
    URL
}

